# Generated by Django 4.0.2 on 2022-04-24 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inspector', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inspect',
            new_name='Ins',
        ),
    ]
