# Generated by Django 4.0.2 on 2022-04-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspector', '0002_rename_inspect_ins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField()),
                ('pic', models.FileField(default='default.jpg', upload_to='Profile')),
            ],
        ),
    ]
