# Generated by Django 4.0.2 on 2022-04-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspector', '0003_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
