# Generated by Django 4.0.2 on 2022-04-28 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Commissioner', '0002_cons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cons',
            old_name='password',
            new_name='phone',
        ),
    ]
