# Generated by Django 4.0.2 on 2022-04-10 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fir',
            name='invest',
        ),
    ]
