# Generated by Django 4.0.2 on 2022-04-13 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('idate', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=6)),
                ('address', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=50)),
                ('charge', models.CharField(max_length=100)),
                ('victim', models.CharField(blank=True, max_length=10, null=True)),
                ('ifname', models.CharField(max_length=50)),
                ('ilname', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('iaddress', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.station')),
            ],
        ),
    ]
