# Generated by Django 4.0.2 on 2022-04-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='invest',
            field=models.BooleanField(default=False),
        ),
    ]
