# Generated by Django 4.0.2 on 2022-04-26 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_complaint_invest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='invest',
        ),
    ]
