# Generated by Django 4.0.2 on 2022-04-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_complaint_invest'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
