# Generated by Django 4.0.2 on 2022-04-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_feedback_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
