# Generated by Django 4.0.2 on 2022-04-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_missing_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='missing',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
